let x: number = 0;

// 덧셈 대입 연산자(+=) 사용 예
x = 5;
console.log(x += 3); // 8
// 뺄셈 대입 연산자(-=) 사용 예
x = 10;
console.log(x -= 3); // 7
// 곱셈 대입 연산자(*=) 사용 예
x = 3;
console.log(x *= 4); // 12
// 나눗셈 대입 연산자(/=) 사용 예
x = 10;
console.log(x /= 2); // 5
// 나머지 대입 연산자(%=) 사용 예
x = 7;
console.log(x %= 3); // 1
// 제곱 대입 연산자(**=) 사용 예
x = 2;
console.log(x **= 3); // 8